permalink:           pretty

# Setup
title:               'Deep Learning'
url:                 https://atcold.github.io/NYU-DLFL22/
baseurl:             '/NYU-DLFL22'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                atcold
url:                 https://twitter.com/alfcnz
github:
  repo:              https://github.com/atcold/NYU-DLFL22

# Custom vars
version:             dlfl22

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - en/index.md
  - vendor


################################### English ####################################
prologues:
  - path: en/faq.md
